package com.allnoneplus.backend.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * OpenAPI documentation configuration (generated by springdoc).
 */
@Configuration
public class OpenApiConfig {

  @Bean
  public OpenAPI allnonePlusOpenApi() {
    return new OpenAPI()
        .info(new Info()
            .title("AllnOne+ Backend API")
            .description(
                "Synchronizes student schedules from the remote planning API and exposes them "
                    + "with persistence for comparison between weeks.")
            .version("1.0.0"));
  }
}
