-- Main table of schedules (slots) fetched from the planning API.
CREATE TABLE schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  external_id VARCHAR(255),
  title TEXT,
  start_time TIMESTAMP WITH TIME ZONE,
  end_time TIMESTAMP WITH TIME ZONE,
  background_color VARCHAR(50),
  border_color VARCHAR(50),
  text_color VARCHAR(50),
  -- extendedProps
  type VARCHAR(100),
  session_type VARCHAR(100),
  session_label VARCHAR(255),
  is_exam_session BOOLEAN,
  is_activity_session BOOLEAN,
  exam_id BIGINT,
  planning_activity_id BIGINT,
  schedule_id BIGINT,
  module VARCHAR(500),
  module_code VARCHAR(100),
  module_id BIGINT,
  teacher VARCHAR(255),
  teacher_id BIGINT,
  room VARCHAR(255),
  room_id BIGINT,
  levels TEXT,
  levels_codes TEXT,
  day_of_week INTEGER,
  start_time_of_day TIME,
  end_time_of_day TIME,
  total_students INTEGER,
  room_capacity INTEGER,
  capacity_exceeded BOOLEAN,
  -- synchronization context
  week_start DATE,
  fetched_at TIMESTAMP WITH TIME ZONE,
  CONSTRAINT uq_schedule_week UNIQUE (schedule_id, week_start)
);
CREATE INDEX idx_schedules_week_start ON schedules (week_start);
-- Join tables for the extendedProps lists
CREATE TABLE schedule_schedule_ids (
  schedule_ref_id BIGINT NOT NULL REFERENCES schedules (id) ON DELETE CASCADE,
  schedule_id_value BIGINT
);
CREATE TABLE schedule_rooms (
  schedule_ref_id BIGINT NOT NULL REFERENCES schedules (id) ON DELETE CASCADE,
  room VARCHAR(255)
);
CREATE TABLE schedule_room_ids (
  schedule_ref_id BIGINT NOT NULL REFERENCES schedules (id) ON DELETE CASCADE,
  room_id BIGINT
);
CREATE TABLE schedule_level_ids (
  schedule_ref_id BIGINT NOT NULL REFERENCES schedules (id) ON DELETE CASCADE,
  level_id BIGINT
);